services:
  db:
    image: postgres:14.2
    container_name: db-container
    environment:
      POSTGRES_DB: <db-name>
      POSTGRES_USER: <db-user>
      POSTGRES_PASSWORD: <db-password>
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    container_name: backend-container
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: <db-name>
      DATABASE_PASSWORD: <db-password>
      APPLICATION_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    container_name: frontend-container
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
